name: deploy

on:
  push:
    branches: [ master ]
jobs:
  update-files:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Update Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/behind.line.pm
            git reset --hard origin/master
            git pull
  build-client:
    if: "contains(github.event.commits[0].message, '[need build client]')"
    timeout-minutes: 2
    needs: [update-files]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Client
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/behind.line.pm/client
            pm2 stop client
            npm install
            npm run build
            pm2 start client --update-env
  deploy-server:
    if: "contains(github.event.commits[0].message, '[need deploy server]')"
    needs: [update-files]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/behind.line.pm/api
            pm2 stop api
            npm install
            npm run start
            pm2 start api --update-env